"""Public typed Flow interfaces.

The external seam is :class:`FlowEngine`; model values and explicit registry
dependencies are re-exported so callers and tests cross the same interface.
"""

from sigilicon.flow.contracts import (
    load_catalog_selection,
    load_execution_profile,
    load_flow_catalog,
    load_flow_contract,
    parse_flow_catalog,
    resolve_catalog_selection,
)
from sigilicon.flow.adapter_result import complete_staged_run
from sigilicon.flow.engine import FlowEngine
from sigilicon.flow.environment import (
    ExecutionEnvironmentContract,
    load_execution_environment,
    load_execution_environment_contract,
)
from sigilicon.flow.fake import fake_profile, fake_registry
from sigilicon.flow.model import (
    ActionArtifact,
    ActionConfiguration,
    ActionContext,
    ActionContract,
    AdapterExecution,
    AdapterConfiguration,
    AdapterResult,
    AdapterResultError,
    AdapterSelection,
    ArtifactBinding,
    ArtifactPort,
    CollectedActionResult,
    DesignCatalogExpansion,
    ExecutionEnvironment,
    ExecutionProfile,
    EvidenceEnvelope,
    FlowCatalog,
    FlowCatalogEntry,
    FlowContractError,
    FlowExecutionError,
    FlowNode,
    FlowPlan,
    FlowProgress,
    FlowResult,
    FlowSpec,
    FlowTarget,
    InputArtifact,
    LayoutCatalogExpansion,
    NodeOutcome,
    PolicyCheck,
    PolicySpec,
    PlatformAssetRequirement,
    PreflightCheck,
    PreflightResult,
    ProducedArtifact,
    ResolvedPlatformAsset,
    ResolvedCapability,
    ResolvedPlatformAssetMember,
    GitSource,
    SourceArtifact,
    SourceAssets,
    SourceMember,
)
from sigilicon.flow.registry import FlowRegistry, ToolAdapter
__all__ = [
    "ActionArtifact",
    "ActionConfiguration",
    "ActionContext",
    "ActionContract",
    "AdapterExecution",
    "AdapterConfiguration",
    "AdapterResult",
    "AdapterResultError",
    "AdapterSelection",
    "ArtifactBinding",
    "ArtifactPort",
    "CollectedActionResult",
    "DesignCatalogExpansion",
    "ExecutionEnvironment",
    "ExecutionEnvironmentContract",
    "ExecutionProfile",
    "EvidenceEnvelope",
    "FlowCatalog",
    "FlowCatalogEntry",
    "FlowContractError",
    "FlowEngine",
    "FlowExecutionError",
    "FlowNode",
    "FlowPlan",
    "FlowProgress",
    "FlowRegistry",
    "FlowResult",
    "FlowSpec",
    "FlowTarget",
    "InputArtifact",
    "LayoutCatalogExpansion",
    "NodeOutcome",
    "PolicyCheck",
    "PolicySpec",
    "PlatformAssetRequirement",
    "PreflightCheck",
    "PreflightResult",
    "ProducedArtifact",
    "ResolvedPlatformAsset",
    "ResolvedCapability",
    "ResolvedPlatformAssetMember",
    "GitSource",
    "SourceArtifact",
    "SourceAssets",
    "SourceMember",
    "ToolAdapter",
    "complete_staged_run",
    "load_flow_contract",
    "load_execution_profile",
    "load_flow_catalog",
    "parse_flow_catalog",
    "load_catalog_selection",
    "resolve_catalog_selection",
    "load_execution_environment",
    "load_execution_environment_contract",
    "fake_registry",
    "fake_profile",
]
