"""Public typed Flow interfaces.

The external seam is :class:`FlowEngine`; model values and explicit registry
dependencies are re-exported so callers and tests cross the same interface.
"""

from sigilicon.flow.contracts import (
    load_catalog_selection,
    load_execution_profile,
    load_flow_catalog,
    load_flow_contract,
)
from sigilicon.flow.builtin import builtin_registry
from sigilicon.flow.engine import FlowEngine
from sigilicon.flow.environment import load_execution_environment
from sigilicon.flow.fake import fake_profile, fake_registry
from sigilicon.flow.model import (
    ActionArtifact,
    ActionContext,
    ActionContract,
    AdapterExecution,
    AdapterSelection,
    ArtifactBinding,
    ArtifactPort,
    CollectedActionResult,
    ExecutionEnvironment,
    ExecutionProfile,
    FlowCatalog,
    FlowCatalogEntry,
    FlowContractError,
    FlowExecutionError,
    FlowNode,
    FlowPlan,
    FlowResult,
    FlowSpec,
    FlowTarget,
    InputArtifact,
    NodeOutcome,
    PolicyCheck,
    PolicySpec,
    PlatformAssetRequirement,
    PreflightCheck,
    PreflightResult,
    ProducedArtifact,
    ResolvedPlatformAsset,
    ResolvedCapability,
    ResolvedPlatformAssetMember,
    GitSource,
    SourceArtifact,
    SourceAssets,
    SourceMember,
)
from sigilicon.flow.registry import FlowRegistry, ToolAdapter
from sigilicon.flow.physical_design import (
    PHYSICAL_CLOSURE_EVIDENCE_KIND,
    PHYSICAL_DESIGN_ACTION,
    PHYSICAL_DESIGN_JOB_KIND,
    PHYSICAL_DESIGN_RESULT_KIND,
    PHYSICAL_DESIGN_SOURCE_ACTION,
    PHYSICAL_MATERIALIZATION_ACTION,
    PHYSICAL_MATERIALIZATION_EXECUTION_ACTION,
    PHYSICAL_MATERIALIZATION_PLAN_KIND,
    MATERIALIZED_GDS_KIND,
    MATERIALIZATION_ACCEPTANCE_EVIDENCE_KIND,
    MATERIALIZATION_RECEIPT_KIND,
    OA_XSTREAM_MATERIALIZATION_ADAPTER,
    REFERENCE_MATERIALIZATION_ADAPTER,
    REFERENCE_PNR_ADAPTER,
    register_physical_design_actions,
)
from sigilicon.flow.physical_verification import (
    CALIBRE_PHYSICAL_VERIFICATION_ADAPTER,
    CANONICAL_SOURCE_NETLIST_KIND,
    DRC_ACTION,
    DRC_EVIDENCE_KIND,
    LVS_ACTION,
    LVS_EVIDENCE_KIND,
    MATERIALIZED_LAYOUT_KIND,
    OFFLINE_PHYSICAL_VERIFICATION_ADAPTER,
    PHYSICAL_VERIFICATION_POLICY_KIND,
    register_physical_verification_actions,
)
from sigilicon.flow.standard_asic import register_standard_asic_actions
from sigilicon.flow.synopsys import (
    SynopsysDCAdapter,
    SynopsysFCAdapter,
    SynopsysHSpiceAdapter,
    SynopsysVCSAdapter,
)
from sigilicon.flow.source_assets import (
    SourceAssetsAdapter,
    load_source_assets,
    source_assets_payload,
)
__all__ = [
    "ActionArtifact",
    "ActionContext",
    "ActionContract",
    "AdapterExecution",
    "AdapterSelection",
    "ArtifactBinding",
    "ArtifactPort",
    "CollectedActionResult",
    "CANONICAL_SOURCE_NETLIST_KIND",
    "CALIBRE_PHYSICAL_VERIFICATION_ADAPTER",
    "DRC_ACTION",
    "DRC_EVIDENCE_KIND",
    "ExecutionEnvironment",
    "ExecutionProfile",
    "FlowCatalog",
    "FlowCatalogEntry",
    "FlowContractError",
    "FlowEngine",
    "FlowExecutionError",
    "FlowNode",
    "FlowPlan",
    "FlowRegistry",
    "FlowResult",
    "FlowSpec",
    "FlowTarget",
    "InputArtifact",
    "LVS_ACTION",
    "LVS_EVIDENCE_KIND",
    "MATERIALIZED_LAYOUT_KIND",
    "NodeOutcome",
    "OFFLINE_PHYSICAL_VERIFICATION_ADAPTER",
    "PHYSICAL_VERIFICATION_POLICY_KIND",
    "PHYSICAL_CLOSURE_EVIDENCE_KIND",
    "PHYSICAL_DESIGN_ACTION",
    "PHYSICAL_DESIGN_JOB_KIND",
    "PHYSICAL_DESIGN_RESULT_KIND",
    "PHYSICAL_DESIGN_SOURCE_ACTION",
    "PHYSICAL_MATERIALIZATION_ACTION",
    "PHYSICAL_MATERIALIZATION_EXECUTION_ACTION",
    "PHYSICAL_MATERIALIZATION_PLAN_KIND",
    "MATERIALIZED_GDS_KIND",
    "MATERIALIZATION_ACCEPTANCE_EVIDENCE_KIND",
    "MATERIALIZATION_RECEIPT_KIND",
    "OA_XSTREAM_MATERIALIZATION_ADAPTER",
    "PolicyCheck",
    "PolicySpec",
    "PlatformAssetRequirement",
    "PreflightCheck",
    "PreflightResult",
    "ProducedArtifact",
    "ResolvedPlatformAsset",
    "ResolvedCapability",
    "ResolvedPlatformAssetMember",
    "REFERENCE_PNR_ADAPTER",
    "REFERENCE_MATERIALIZATION_ADAPTER",
    "GitSource",
    "SourceArtifact",
    "SourceAssets",
    "SourceMember",
    "SourceAssetsAdapter",
    "ToolAdapter",
    "load_flow_contract",
    "load_execution_profile",
    "load_flow_catalog",
    "load_catalog_selection",
    "load_execution_environment",
    "fake_registry",
    "fake_profile",
    "register_standard_asic_actions",
    "register_physical_design_actions",
    "register_physical_verification_actions",
    "SynopsysDCAdapter",
    "SynopsysFCAdapter",
    "SynopsysHSpiceAdapter",
    "SynopsysVCSAdapter",
    "builtin_registry",
    "load_source_assets",
    "source_assets_payload",
]
