"""Public typed Flow interfaces.

The external seam is :class:`FlowEngine`; model values and explicit registry
dependencies are re-exported so callers and tests cross the same interface.
"""

from sigilicon.flow.contracts import (
    compile_flow_spec,
    load_execution_recipe,
    parse_execution_recipe,
)
from sigilicon.flow.adapter_result import complete_staged_run
from sigilicon.flow.engine import FlowEngine
from sigilicon.flow.environment import (
    ExecutionEnvironmentContract,
    load_execution_environment,
    load_execution_environment_contract,
)
from sigilicon.flow.model import (
    ActionArtifact,
    ActionConfiguration,
    ActionContext,
    ActionContract,
    ActionPlan,
    ActionBinding,
    AdapterExecution,
    AdapterConfiguration,
    AdapterResult,
    AdapterResultError,
    ArtifactBinding,
    ArtifactPort,
    CollectedActionResult,
    ExecutionRecipe,
    ExecutionEnvironment,
    EvidenceEnvelope,
    FlowContractError,
    FlowExecutionError,
    FlowNode,
    FlowPlan,
    FlowProgress,
    FlowResult,
    FlowSpec,
    FlowTarget,
    InputArtifact,
    NodeOutcome,
    PolicyCheck,
    PolicySpec,
    PlatformAssetRequirement,
    PreflightCheck,
    PreflightResult,
    ProducedArtifact,
    ResolvedPlatformAsset,
    ResolvedCapability,
    ResolvedPlatformAssetMember,
    GitSource,
    SourceArtifact,
    SourceAssets,
    SourceMember,
)
from sigilicon.flow.registry import FlowRegistry, ToolAdapter
__all__ = [
    "ActionArtifact",
    "ActionConfiguration",
    "ActionContext",
    "ActionContract",
    "ActionPlan",
    "AdapterExecution",
    "AdapterConfiguration",
    "AdapterResult",
    "AdapterResultError",
    "ActionBinding",
    "ArtifactBinding",
    "ArtifactPort",
    "CollectedActionResult",
    "ExecutionRecipe",
    "ExecutionEnvironment",
    "ExecutionEnvironmentContract",
    "EvidenceEnvelope",
    "FlowContractError",
    "FlowEngine",
    "FlowExecutionError",
    "FlowNode",
    "FlowPlan",
    "FlowProgress",
    "FlowRegistry",
    "FlowResult",
    "FlowSpec",
    "FlowTarget",
    "InputArtifact",
    "NodeOutcome",
    "PolicyCheck",
    "PolicySpec",
    "PlatformAssetRequirement",
    "PreflightCheck",
    "PreflightResult",
    "ProducedArtifact",
    "ResolvedPlatformAsset",
    "ResolvedCapability",
    "ResolvedPlatformAssetMember",
    "GitSource",
    "SourceArtifact",
    "SourceAssets",
    "SourceMember",
    "ToolAdapter",
    "complete_staged_run",
    "compile_flow_spec",
    "load_execution_recipe",
    "parse_execution_recipe",
    "load_execution_environment",
    "load_execution_environment_contract",
]
