"""General physical-design problem solving.

The public Interface is :func:`run` plus immutable normalized input and result
values. Database and project formats belong in adapters outside this Module.
"""

from sigilicon.layout.pnr.engine import PnrInputError, run
from sigilicon.layout.pnr.model import (
    AlignmentAnchor,
    AlignmentConstraint,
    ArrayConstraint,
    Axis,
    ConstraintMode,
    ConstraintOutcome,
    ConstraintStatus,
    Diagnostic,
    FenceConstraint,
    InstancePlacement,
    LayerKind,
    MasterPin,
    Metric,
    Orientation,
    OrderingConstraint,
    PhysicalDesign,
    PhysicalDesignJob,
    PhysicalDesignResult,
    PhysicalInstance,
    PhysicalLayer,
    PhysicalMaster,
    PhysicalNet,
    PhysicalPort,
    PhysicalTechnology,
    PinAccess,
    PinReference,
    Placement,
    PlacementConstraint,
    PnrProvenance,
    PnrRequest,
    PnrStage,
    Point,
    Rect,
    ResultStatus,
    RoutingDirection,
    SeparationAxis,
    SeparationConstraint,
    StageReport,
    SymmetryConstraint,
)

__all__ = [
    "AlignmentAnchor",
    "AlignmentConstraint",
    "ArrayConstraint",
    "Axis",
    "ConstraintMode",
    "ConstraintOutcome",
    "ConstraintStatus",
    "Diagnostic",
    "FenceConstraint",
    "InstancePlacement",
    "LayerKind",
    "MasterPin",
    "Metric",
    "Orientation",
    "OrderingConstraint",
    "PhysicalDesign",
    "PhysicalDesignJob",
    "PhysicalDesignResult",
    "PhysicalInstance",
    "PhysicalLayer",
    "PhysicalMaster",
    "PhysicalNet",
    "PhysicalPort",
    "PhysicalTechnology",
    "PinAccess",
    "PinReference",
    "Placement",
    "PlacementConstraint",
    "PnrInputError",
    "PnrProvenance",
    "PnrRequest",
    "PnrStage",
    "Point",
    "Rect",
    "ResultStatus",
    "RoutingDirection",
    "SeparationAxis",
    "SeparationConstraint",
    "StageReport",
    "SymmetryConstraint",
    "run",
]
