"""General physical-design problem solving.

The public Interface is :func:`run` plus immutable normalized input and result
values. Database and project formats belong in adapters outside this Module.
"""

from sigilicon.layout.pnr.engine import PnrInputError, run
from sigilicon.layout.pnr.model import (
    ConstraintMode,
    ConstraintOutcome,
    ConstraintStatus,
    Diagnostic,
    FenceConstraint,
    InstancePlacement,
    LayerKind,
    MasterPin,
    Metric,
    Orientation,
    PhysicalDesign,
    PhysicalDesignJob,
    PhysicalDesignResult,
    PhysicalInstance,
    PhysicalLayer,
    PhysicalMaster,
    PhysicalNet,
    PhysicalPort,
    PhysicalTechnology,
    PinAccess,
    PinReference,
    Placement,
    PnrProvenance,
    PnrRequest,
    PnrStage,
    Point,
    Rect,
    ResultStatus,
    RoutingDirection,
    StageReport,
)

__all__ = [
    "ConstraintMode",
    "ConstraintOutcome",
    "ConstraintStatus",
    "Diagnostic",
    "FenceConstraint",
    "InstancePlacement",
    "LayerKind",
    "MasterPin",
    "Metric",
    "Orientation",
    "PhysicalDesign",
    "PhysicalDesignJob",
    "PhysicalDesignResult",
    "PhysicalInstance",
    "PhysicalLayer",
    "PhysicalMaster",
    "PhysicalNet",
    "PhysicalPort",
    "PhysicalTechnology",
    "PinAccess",
    "PinReference",
    "Placement",
    "PnrInputError",
    "PnrProvenance",
    "PnrRequest",
    "PnrStage",
    "Point",
    "Rect",
    "ResultStatus",
    "RoutingDirection",
    "StageReport",
    "run",
]
